version: '3'

services:
  alert_bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./d–∞ta:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}

networks:
  backend:
