services:
  alert_bot:
    container_name: alert_bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    restart: unless-stopped
    networks:
      - alertbot
    volumes:
      - alert_bot_data:/app/data

networks:
  alertbot:

volumes:
  alert_bot_data:
